name = "uptimeflare_worker"
main = "src/index.ts"
compatibility_date = "2025-04-02"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "UPTIMEFLARE_D1"
database_name = "uptimeflare_d1"
database_id = "66a312fc-4f87-4631-a438-623b4e4b5916"

[[durable_objects.bindings]]
name = "REMOTE_CHECKER_DO"
class_name = "RemoteChecker"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RemoteChecker"]
